# linux distribution to be used in VM
dist: xenial

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

# before_install:
before_script:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://lf-travis-shared-storage/$TRAVIS_BUILD_NUMBER/$TIER ~/$TRAVIS_BUILD_NUMBER/$TIER
  - unzip -q ~/$TRAVIS_BUILD_NUMBER/$TIER/$TIER.zip -d ./ || true
  - ls -al
# before_script:
  - npm install -g serverless
  - npm install -g serverless-single-page-app-plugin  

cache:
  directories:
    - ~/api/node_modules
    - ~/app/node_modules


jobs:
  include:
    - stage: build
      language: node_js
      node_js: "8.10"
      
      name: "Build API"  
      script: |
                cd api
                npm install
      env: TIER=api
                      
    - script: |
                cd app
                npm install
      
      name: "Build APP"  
      env: TIER=app
      
    - stage: deploy
      language: node_js
      node_js: "8.10"            
    
      name: "Deploy APP"  
      script: |
                echo "Deploying frontend"
                cd devops/frontend
                npm install
                serverless deploy
                serverless syncToS3
      env: TIER=app
      
    - script: |
                echo "Deploying the backend"
                cd devops/backend
                npm install serverless-package-external 
                npm install serverless-http --save
                serverless deploy
      name: "Deploy API" 
      env: TIER=api


#       after_success:
#               - aws s3 rm --recursive s3://lf-travis-shared-storage/$TRAVIS_BUILD_NUMBER # clean up after ourselves
        
after_success:
  - zip -r -q ~/$TRAVIS_BUILD_NUMBER/$TIER/$TIER.zip /home/travis/build/pravash-upreti/serverless-pipeline/$TIER/*
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER/$TIER s3://lf-travis-shared-storage/$TRAVIS_BUILD_NUMBER/$TIER
