# linux distribution to be used in VM
dist: xenial

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

# before_install:
before_script:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://lf-travis-shared-storage/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
# before_script:
  - npm install -g serverless
  - npm install -g serverless-single-page-app-plugin  

cache:
  directories:
    - ~/api/node_modules
    - ~/app/node_modules

matrix:
  - node_js=8.10
  - node_js=8.10

jobs:
  include:
    - stage: build
      language: node_js
      node_js: "8.10"
      cache:
        directories:
          - "node_modules"
        yarn: true
      
      name: "Build API"  
      
      script: |
                cd api
                npm install
      
      name: "Build APP"                  
      script: |
                cd app
                npm install
      
      branches:
        only:
        - ci-config
        - dev
        - master      
      
    - stage: deploy
      language: node_js
      node_js: "8.10"
      before_install:
        - | 
            sudo apt-get update
            
      branches:
        only:
        - dev
        - ci-config
        - master
      
      name: "Deploy APP"  
      script: |
                echo "Deploying frontend"
                cd devops/frontend
                npm install
                serverless deploy
                serverless syncToS3
      
      name: "Deploy API"  
      script: |
                echo "Deploying the backend"
                cd devops/backend
                npm install serverless-package-external 
                npm install serverless-http --save
                serverless deploy


#       after_success:
#               - aws s3 rm --recursive s3://lf-travis-shared-storage/$TRAVIS_BUILD_NUMBER # clean up after ourselves
        
after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://lf-travis-shared-storage/$TRAVIS_BUILD_NUMBER
